export enum ApplicantType {
  PETITIONER = 'PETITIONER',
  BENEFICIARY = 'BENEFICIARY',
  PRINCIPAL_BENEFICIARY = 'PRINCIPAL_BENEFICIARY',
  DERIVATIVE_BENEFICIARY = 'DERIVATIVE_BENEFICIARY',
  PRIMARY_APPLICANT = 'PRIMARY_APPLICANT',
}
