import { BenefitGroups } from './benefit-groups.enum';

export interface BenefitGroup {
  value: BenefitGroups;
  label: string;
}

export const benefitGroups: BenefitGroup[] = [
  {value: BenefitGroups.IMMEDIATE_RELATIVE_VISA, label: 'TEMPLATE.IMMIGRATION_BENEFIT_CATEGORIES.IMMEDIATE_RELATIVE_VISA_TITLE'},
  {value: BenefitGroups.FAMILY_PREFERENCE_VISA, label: 'TEMPLATE.IMMIGRATION_BENEFIT_CATEGORIES.FAMILY_PREFERENCE_VISA_TITLE'},
  {value: BenefitGroups.VISA_FIANCE_SPOUSE, label: 'TEMPLATE.IMMIGRATION_BENEFIT_CATEGORIES.VISA_FIANCE_SPOUSE_OF_CITIZEN_TITLE'},
  {value: BenefitGroups.NATURALIZATION, label: 'TEMPLATE.IMMIGRATION_BENEFIT_CATEGORIES.NATURALIZATION'},
  {value: BenefitGroups.PERMANENT_RESIDENCE, label: 'TEMPLATE.IMMIGRATION_BENEFIT_CATEGORIES.PERMANENT_RESIDENCE_TITLE'},
  {value: BenefitGroups.MISCELLANEOUS, label: 'TEMPLATE.IMMIGRATION_BENEFIT_CATEGORIES.MISCELLANEOUS'},
  {value: BenefitGroups.REMOVE_CONDITIONS, label: 'TEMPLATE.IMMIGRATION_BENEFIT_CATEGORIES.REMOVE_CONDITIONS_TITLE'},
];
