export enum RegistrationStatus {
  NEW = 'NEW',
  EMAIL_VERIFIED = 'EMAIL_VERIFIED',
  REPRESENTATIVE_SELECTED = 'REPRESENTATIVE_SELECTED',
  CONTACT_INFO_UPDATED = 'CONTACT_INFO_UPDATED',
  COMPLETE = 'COMPLETE',
  CONVERT_TO_ATTORNEY = 'CONVERT_TO_ATTORNEY',
}
