package com.easyvisa.enums

enum Country {

    ABKHAZIA_REPUBLIC_OF_ABKHAZIA('Abkhazia – Republic of Abkhazia'),
    AFGHANISTAN('Afghanistan'),
    ALBANIA('Albania'),
    ALGERIA('Algeria'),
    AMERICAN_SAMOA('American Samoa'),
    ANDORRA('Andorra'),
    ANGOLA('Angola'),
    ANGUILLA('Anguilla'),
    ANTIGUA_AND_BARBUDA('Antigua and Barbuda'),
    ARGENTINA('Argentina'),
    ARMENIA('Armenia'),
    ARUBA('Aruba'),
    AUSTRALIA('Australia'),
    AUSTRIA('Austria'),
    AZERBAIJAN('Azerbaijan'),
    BAHAMAS('Bahamas'),
    BAHRAIN('Bahrain'),
    BANGLADESH('Bangladesh'),
    BARBADOS('Barbados'),
    BELARUS('Belarus'),
    BELGIUM('Belgium'),
    BELIZE('Belize'),
    BENIN('Benin'),
    BERMUDA('Bermuda'),
    BHUTAN('Bhutan'),
    BOLIVIA('Bolivia'),
    BOSNIA_HERZEGOVINA('Bosnia-Herzegovina'),
    BOTSWANA('Botswana'),
    BOUVET_ISLAND('Bouvet Island'),
    BRAZIL('Brazil'),
    BRUNEI('Brunei'),
    BULGARIA('Bulgaria'),
    BURKINA_FASO('Burkina Faso'),
    BURUNDI('Burundi'),
    CAMBODIA('Cambodia'),
    CAMEROON('Cameroon'),
    CANADA('Canada'),
    CAPE_VERDE('Cape Verde'),
    CAYMAN_ISLANDS('Cayman Islands'),
    CENTRAL_AFRICAN_REPUBLIC('Central African Republic'),
    CHAD('Chad'),
    CHILE('Chile'),
    CHINA('China'),
    CHINA_TAIWAN('China - Taiwan'),
    CHRISTMAS_ISLAND('Christmas Island'),
    COCOS_KEELING_ISLANDS('Cocos (Keeling) Islands'),
    COLOMBIA('Colombia'),
    COMOROS('Comoros'),
    CONGO_DEMOCRATIC_REPUBLIC_OF_THE_ZAIRE('Congo, Democratic Republic of the (Zaire)'),
    CONGO_REPUBLIC_OF('Congo, Republic of'),
    COOK_ISLANDS('Cook Islands'),
    COSTA_RICA('Costa Rica'),
    CROATIA('Croatia'),
    CUBA('Cuba'),
    CYPRUS('Cyprus'),
    CZECH_REPUBLIC('Czech Republic'),
    DENMARK('Denmark'),
    DJIBOUTI('Djibouti'),
    DOMINICA('Dominica'),
    DOMINICAN_REPUBLIC('Dominican Republic'),
    EAST_TIMOR_TIMOR_LESTE('East Timor (Timor-Leste)'),
    ECUADOR('Ecuador'),
    EGYPT('Egypt'),
    EL_SALVADOR('El Salvador'),
    EQUATORIAL_GUINEA('Equatorial Guinea'),
    ERITREA('Eritrea'),
    ESTONIA('Estonia'),
    ETHIOPIA('Ethiopia'),
    FALKLAND_ISLANDS('Falkland Islands'),
    FAROE_ISLANDS('Faroe Islands'),
    FIJI('Fiji'),
    FINLAND('Finland'),
    FRANCE('France'),
    FRENCH_GUIANA('French Guiana'),
    GABON('Gabon'),
    GAMBIA('Gambia'),
    GEORGIA('Georgia'),
    GERMANY('Germany'),
    GHANA('Ghana'),
    GIBRALTAR('Gibraltar'),
    GREECE('Greece'),
    GREENLAND('Greenland'),
    GRENADA('Grenada'),
    GUADELOUPE_FRENCH('Guadeloupe (French)'),
    GUAM_USA('Guam (USA)'),
    GUATEMALA('Guatemala'),
    GUINEA('Guinea'),
    GUINEA_BISSAU('Guinea Bissau'),
    GUYANA('Guyana'),
    HAITI('Haiti'),
    HOLY_SEE('Holy See'),
    HONDURAS('Honduras'),
    HONG_KONG('Hong Kong'),
    HUNGARY('Hungary'),
    ICELAND('Iceland'),
    INDIA('India'),
    INDONESIA('Indonesia'),
    IRAN('Iran'),
    IRAQ('Iraq'),
    IRELAND('Ireland'),
    ISRAEL('Israel'),
    ITALY('Italy'),
    IVORY_COAST_COTE_DIVOIRE('Ivory Coast (Cote D`Ivoire)'),
    JAMAICA('Jamaica'),
    JAPAN('Japan'),
    JORDAN('Jordan'),
    KAZAKHSTAN('Kazakhstan'),
    KENYA('Kenya'),
    KIRIBATI('Kiribati'),
    KOSOVO_REPUBLIC_OF_KOSOVO('Kosovo – Republic of Kosovo'),
    KUWAIT('Kuwait'),
    KYRGYZSTAN('Kyrgyzstan'),
    LAOS('Laos'),
    LATVIA('Latvia'),
    LEBANON('Lebanon'),
    LESOTHO('Lesotho'),
    LIBERIA('Liberia'),
    LIBYA('Libya'),
    LIECHTENSTEIN('Liechtenstein'),
    LITHUANIA('Lithuania'),
    LUXEMBOURG('Luxembourg'),
    MACAU('Macau'),
    MACEDONIA('Macedonia'),
    MADAGASCAR('Madagascar'),
    MALAWI('Malawi'),
    MALAYSIA('Malaysia'),
    MALDIVES('Maldives'),
    MALI('Mali'),
    MALTA('Malta'),
    MARSHALL_ISLANDS('Marshall Islands'),
    MARTINIQUE_FRENCH('Martinique (French)'),
    MAURITANIA('Mauritania'),
    MAURITIUS('Mauritius'),
    MAYOTTE('Mayotte'),
    MEXICO('Mexico'),
    MICRONESIA('Micronesia'),
    MOLDOVA('Moldova'),
    MONACO('Monaco'),
    MONGOLIA('Mongolia'),
    MONTENEGRO('Montenegro'),
    MONTSERRAT('Montserrat'),
    MOROCCO('Morocco'),
    MOZAMBIQUE('Mozambique'),
    MYANMAR('Myanmar'),
    NAGORNO_KARABAKH_NAGORNO_KARABAKH_REPUBLIC('Nagorno-Karabakh – Nagorno-Karabakh Republic'),
    NAMIBIA('Namibia'),
    NAURU('Nauru'),
    NEPAL('Nepal'),
    NETHERLANDS('Netherlands'),
    NETHERLANDS_ANTILLES('Netherlands Antilles'),
    NEW_CALEDONIA_FRENCH('New Caledonia (French)'),
    NEW_ZEALAND('New Zealand'),
    NICARAGUA('Nicaragua'),
    NIGER('Niger'),
    NIGERIA('Nigeria'),
    NIUE('Niue'),
    NORFOLK_ISLAND('Norfolk Island'),
    NORTH_KOREA('North Korea'),
    NORTHERN_CYPRUS_TURKISH_REPUBLIC_OF_NORTHERN_CYPRUS('Northern Cyprus – Turkish Republic of Northern Cyprus'),
    NORTHERN_MARIANA_ISLANDS('Northern Mariana Islands'),
    NORWAY('Norway'),
    OMAN('Oman'),
    PAKISTAN('Pakistan'),
    PALAU('Palau'),
    PANAMA('Panama'),
    PAPUA_NEW_GUINEA('Papua New Guinea'),
    PARAGUAY('Paraguay'),
    PERU('Peru'),
    PHILIPPINES('Philippines'),
    PITCAIRN_ISLAND('Pitcairn Island'),
    POLAND('Poland'),
    POLYNESIA_FRENCH('Polynesia (French)'),
    PORTUGAL('Portugal'),
    PUERTO_RICO('Puerto Rico'),
    QATAR('Qatar'),
    REUNION('Reunion'),
    ROMANIA('Romania'),
    RUSSIA('Russia'),
    RWANDA('Rwanda'),
    SAHRAWI_ARAB_DEMOCRATIC_REPUBLIC('Sahrawi Arab Democratic Republic'),
    SAINT_HELENA('Saint Helena'),
    SAINT_KITTS_AND_NEVIS('Saint Kitts and Nevis'),
    SAINT_LUCIA('Saint Lucia'),
    SAINT_PIERRE_AND_MIQUELON('Saint Pierre and Miquelon'),
    SAINT_VINCENT_AND_GRENADINES('Saint Vincent and Grenadines'),
    SAMOA('Samoa'),
    SAN_MARINO('San Marino'),
    SAO_TOME_AND_PRINCIPE('Sao Tome and Principe'),
    SAUDI_ARABIA('Saudi Arabia'),
    SENEGAL('Senegal'),
    SERBIA('Serbia'),
    SEYCHELLES('Seychelles'),
    SIERRA_LEONE('Sierra Leone'),
    SINGAPORE('Singapore'),
    SLOVAKIA('Slovakia'),
    SLOVENIA('Slovenia'),
    SOLOMON_ISLANDS('Solomon Islands'),
    SOMALIA('Somalia'),
    SOMALILAND_REPUBLIC_OF_SOMALILAND('Somaliland – Republic of Somaliland'),
    SOUTH_AFRICA('South Africa'),
    SOUTH_GEORGIA_AND_SOUTH_SANDWICH_ISLANDS('South Georgia and South Sandwich Islands'),
    SOUTH_KOREA('South Korea'),
    SOUTH_OSSETIA_REPUBLIC_OF_SOUTH_OSSETIA('South Ossetia – Republic of South Ossetia'),
    SOUTH_SUDAN('South Sudan'),
    SPAIN('Spain'),
    SRI_LANKA('Sri Lanka'),
    SUDAN('Sudan'),
    SURINAME('Suriname'),
    SVALBARD_AND_JAN_MAYEN_ISLANDS('Svalbard and Jan Mayen Islands'),
    SWAZILAND('Swaziland'),
    SWEDEN('Sweden'),
    SWITZERLAND('Switzerland'),
    SYRIA('Syria'),
    TAJIKISTAN('Tajikistan'),
    TANZANIA('Tanzania'),
    THAILAND('Thailand'),
    TOGO('Togo'),
    TOKELAU('Tokelau'),
    TONGA('Tonga'),
    TRANSNISTRIA_PRIDNESTROVIAN_MOLDAVIAN_REPUBLIC('Transnistria – Pridnestrovian Moldavian Republic'),
    TRINIDAD_AND_TOBAGO('Trinidad and Tobago'),
    TUNISIA('Tunisia'),
    TURKEY('Turkey'),
    TURKMENISTAN('Turkmenistan'),
    TURKS_AND_CAICOS_ISLANDS('Turks and Caicos Islands'),
    TUVALU('Tuvalu'),
    UGANDA('Uganda'),
    UKRAINE('Ukraine'),
    UNITED_ARAB_EMIRATES('United Arab Emirates'),
    UNITED_KINGDOM('United Kingdom'),
    UNITED_STATES('United States'),
    URUGUAY('Uruguay'),
    UZBEKISTAN('Uzbekistan'),
    VANUATU('Vanuatu'),
    VATICAN_CITY_STATE('Vatican City State'),
    VENEZUELA('Venezuela'),
    VIETNAM('Vietnam'),
    VIRGIN_ISLANDS('Virgin Islands'),
    WALLIS_AND_FUTUNA_ISLANDS('Wallis and Futuna Islands'),
    YEMEN('Yemen'),
    ZAMBIA('Zambia'),
    ZIMBABWE('Zimbabwe'),

    final String displayName

    Country(String displayName) {
        this.displayName = displayName
    }

    String getDisplayName() {
        this.displayName
    }
}