package com.easyvisa.enums

import static com.easyvisa.enums.EmailTemplateType.*

enum EmailTemplateVariable {

    //Variables
    //package
    PETITIONER_NAME(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, DOCUMENT_REJECTION_NOTIFICATION,
                                                    QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD,
                                                    MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE,
                                                    WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),
    PETITIONER_FULL_NAME(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, DOCUMENT_REJECTION_NOTIFICATION,
                                                         QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD,
                                                         MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE,
                                                         WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),
    BENEFICIARY_NAME(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, DOCUMENT_REJECTION_NOTIFICATION,
                                                     QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD,
                                                     MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE,
                                                     WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),
    BENEFICIARY_FULL_NAME(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, DOCUMENT_REJECTION_NOTIFICATION,
                                                          QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD,
                                                          MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE,
                                                          WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),
    PACKAGE_CLIENT_OWED(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, DOCUMENT_REJECTION_NOTIFICATION,
                                                        QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD,
                                                        MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE,
                                                        WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),
    BENEFICIARIES(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, DOCUMENT_REJECTION_NOTIFICATION,
                                                  QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD,
                                                  MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE,
                                                  WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),
    APPLICANT_NAME(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, QUESTIONNAIRE_INACTIVITY,
                                                   DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD, MARRIAGE_IN_90_DAYS_OF_ARRIVAL,
                                                   REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE, WORK_AUTHORIZATION,
                                                   NOT_SUPPORTED_IMMIGRATION_PROCESS],
            null, true),
    APPLICANT_FULL_NAME(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, QUESTIONNAIRE_INACTIVITY,
                                                        DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD, MARRIAGE_IN_90_DAYS_OF_ARRIVAL,
                                                        REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE, WORK_AUTHORIZATION,
                                                        NOT_SUPPORTED_IMMIGRATION_PROCESS],
            null, true),
    PACKAGE_ID(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, DOCUMENT_REJECTION_NOTIFICATION,
                                               QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD,
                                               MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE,
                                               WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES],
            null, false),
    PACKAGE_NAME(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, DOCUMENT_REJECTION_NOTIFICATION,
                                                 QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD,
                                                 MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE,
                                                 WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES],
            null, false),
    ORG_NAME(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, DOCUMENT_REJECTION_NOTIFICATION,
                                             QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD,
                                             MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE,
                                             WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),

    //attorney
    LEGAL_REP_EMAIL(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, INVITE_COLLEAGUE_TO_EASYVISA,
                                                    DOCUMENT_REJECTION_NOTIFICATION, QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY,
                                                    PERMANENT_RESIDENCE_CARD, MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE,
                                                    MARRIAGE_CERTIFICATE, WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),
    LEGAL_REP_PHONE(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, INVITE_COLLEAGUE_TO_EASYVISA,
                                                    DOCUMENT_REJECTION_NOTIFICATION, QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY,
                                                    PERMANENT_RESIDENCE_CARD, MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE,
                                                    MARRIAGE_CERTIFICATE, WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),
    LEGAL_REP_MOBILE(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, INVITE_COLLEAGUE_TO_EASYVISA,
                                                     DOCUMENT_REJECTION_NOTIFICATION, QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY,
                                                     PERMANENT_RESIDENCE_CARD, MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE,
                                                     MARRIAGE_CERTIFICATE, WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),
    LEGAL_REP_FAX(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, INVITE_COLLEAGUE_TO_EASYVISA,
                                                  DOCUMENT_REJECTION_NOTIFICATION, QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY,
                                                  PERMANENT_RESIDENCE_CARD, MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE,
                                                  MARRIAGE_CERTIFICATE, WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),
    LEGAL_REP_NAME(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, INVITE_COLLEAGUE_TO_EASYVISA,
                                                   DOCUMENT_REJECTION_NOTIFICATION, QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY,
                                                   PERMANENT_RESIDENCE_CARD, MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE,
                                                   MARRIAGE_CERTIFICATE, WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),
    REPRESENTATIVE_TYPE(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, INVITE_COLLEAGUE_TO_EASYVISA,
                                                        DOCUMENT_REJECTION_NOTIFICATION, QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY,
                                                        PERMANENT_RESIDENCE_CARD, MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE,
                                                        MARRIAGE_CERTIFICATE, WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),
    LEGAL_REP_FULL_NAME(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, INVITE_COLLEAGUE_TO_EASYVISA,
                                                        DOCUMENT_REJECTION_NOTIFICATION, QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY,
                                                        PERMANENT_RESIDENCE_CARD, MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE,
                                                        MARRIAGE_CERTIFICATE, WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES]),

    //document portal
    DOCUMENT_FILE_NAME(TemplateVariableType.VARIABLE, [DOCUMENT_REJECTION_NOTIFICATION], null, false),
//    DOCUMENT_REJECTION_REASON(TemplateVariableType.VARIABLE, null, false),
    DOCUMENT_UPLOADER_NAME(TemplateVariableType.VARIABLE, [DOCUMENT_REJECTION_NOTIFICATION], null, false),
    DOCUMENT_UPLOADER_FULL_NAME(TemplateVariableType.VARIABLE, [DOCUMENT_REJECTION_NOTIFICATION], null, false),
    DOCUMENT_UPLOAD_DATE(TemplateVariableType.VARIABLE, [DOCUMENT_REJECTION_NOTIFICATION], null, false),
    DOCUMENT_PANEL_NAME(TemplateVariableType.VARIABLE, [DOCUMENT_REJECTION_NOTIFICATION], null, false),
    DOCUMENT_SUB_PANEL_NAME(TemplateVariableType.VARIABLE, [], null, false),

    //reminders
    QUESTIONNAIRE_INACTIVE_INTERVAL(TemplateVariableType.VARIABLE, [QUESTIONNAIRE_INACTIVITY]),
    DOCUMENTS_INACTIVE_INTERVAL(TemplateVariableType.VARIABLE, [DOCUMENT_PORTAL_INACTIVITY]),
    MARRIAGE_EXPIRATION(TemplateVariableType.VARIABLE, [MARRIAGE_IN_90_DAYS_OF_ARRIVAL]),

    //referral discount
    REFERRAL_DISCOUNT(TemplateVariableType.VARIABLE, [INVITE_COLLEAGUE_TO_EASYVISA]),

    //client registration
    REGISTER_APPLICANT_LINK(TemplateVariableType.VARIABLE, [INVITE_APPLICANT], null, false),

    //new employee
    EMPLOYEE_EASYVISA_ID(TemplateVariableType.VARIABLE, [], null, false),
    EMPLOYEE_REGISTRATION_LINK(TemplateVariableType.VARIABLE, [], null, false),
    ADMIN_NAME(TemplateVariableType.VARIABLE, [], null, true),
    ADMIN_FULL_NAME(TemplateVariableType.VARIABLE, [], null, true),

    //url to the application login
    LOGIN_URL(TemplateVariableType.VARIABLE, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, INVITE_COLLEAGUE_TO_EASYVISA,
                                              QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD,
                                              MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE,
                                              WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES],
            null, true),

//    RECIPIENT_EV_ID(TemplateVariableType.VARIABLE, null, false),


    //Fragments
    //attorney
    LEGAL_REP_ADDRESS(TemplateVariableType.FRAGMENT, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, INVITE_COLLEAGUE_TO_EASYVISA,
                                                      DOCUMENT_REJECTION_NOTIFICATION, QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY,
                                                      PERMANENT_RESIDENCE_CARD, MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE,
                                                      MARRIAGE_CERTIFICATE, WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES],
            LEGAL_REPRESENTATIVE_ADDRESS),
    LEGAL_FEES(TemplateVariableType.FRAGMENT, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, INVITE_COLLEAGUE_TO_EASYVISA,
                                               DOCUMENT_REJECTION_NOTIFICATION, QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY,
                                               PERMANENT_RESIDENCE_CARD, MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE,
                                               MARRIAGE_CERTIFICATE, WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES],
            LEGAL_FEES_NEW),
//    RETAINER_AGREEMENT_TEXT(TemplateVariableType.FRAGMENT, EmailTemplateType.RETAINER_AGREEMENT_NEW),

    //package
    APPLICANTS(TemplateVariableType.FRAGMENT, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, DOCUMENT_REJECTION_NOTIFICATION,
                                               QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD,
                                               MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE,
                                               WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES],
            LIST_OF_BENEFICIARIES),
    APPLICANT_LIST(TemplateVariableType.FRAGMENT, [NEW_CLIENT, UPDATED_CLIENT, INVITE_APPLICANT, DOCUMENT_REJECTION_NOTIFICATION,
                                                   QUESTIONNAIRE_INACTIVITY, DOCUMENT_PORTAL_INACTIVITY, PERMANENT_RESIDENCE_CARD,
                                                   MARRIAGE_IN_90_DAYS_OF_ARRIVAL, REMOVAL_CONDITIONS_RESIDENCE, MARRIAGE_CERTIFICATE,
                                                   WORK_AUTHORIZATION, NOT_SUPPORTED_IMMIGRATION_PROCESS, ADDITIONAL_FEES],
            EmailTemplateType.APPLICANT_LIST),

    //only additional fee table
    FEE_TABLE(TemplateVariableType.FRAGMENT, [ADDITIONAL_FEES], EmailTemplateType.FEE_TABLE),

    //reminders
    MISSING_DOCUMENTATION(TemplateVariableType.FRAGMENT, [DOCUMENT_PORTAL_INACTIVITY], EmailTemplateType.MISSING_DOCUMENTATION)

    final TemplateVariableType type
    //it uses to collect variables for displaying them to users for a particular email template
    final List<EmailTemplateType> emailTemplates
    final EmailTemplateType templateType
    final Boolean isPreviewAble

    EmailTemplateVariable(TemplateVariableType type, List<EmailTemplateType> emailTemplates = [],
                          EmailTemplateType templateType = null, isPreviewAble = true) {
        this.type = type
        this.emailTemplates = emailTemplates
        this.templateType = templateType
        this.isPreviewAble = isPreviewAble
    }

    Boolean getIsNotPreviewable() {
        !this.isPreviewAble
    }

    static List<EmailTemplateVariable> getEmailTemplateVariables(EmailTemplateType emailTemplateType) {
        values().findAll { it.emailTemplates.contains(emailTemplateType) }
    }

}

