package com.easyvisa.enums

enum ErrorMessageType {

    PAYMENT_FAILED,
    IMMIGRATION_CATEGORY_CONFLICT,
    BLOCKED_OPEN_PACKAGES,
    MEMBERS_OF_BLOCKED_PACKAGE,
    PAYMENT_CHARGED,
    MEMBERS_WITH_PENDING_OR_DENY_STATUS,
    ALONE_ADMIN,
    ASSIGNED_PACKAGES,
    INVALID_QUESTIONNAIRE_ACCESS,
    INVALID_DOCUMENTPORTAL_ACCESS,
    REMINDER_APPLICANT_INVITATION,
    REMINDER_APPLICANT_PERMISSION,
    INVITATION_ALREADY_ACCEPTED

}