export enum NotificationsSettingType {
  PETITIONER_DOCUMENT = 'PETITIONER_DOCUMENT',
  ALERT = 'ALERT',
  WARNING = 'WARNING',
  BENEFICIARY_DOCUMENT = 'BENEFICIARY_DOCUMENT',
  APPLICANT_REGISTRATION = 'APPLICANT_REGISTRATION',
  QUESTIONNAIRE_COMPLETE = 'QUESTIONNAIRE_COMPLETE',
  DOCUMENTATION_COMPLETE = 'DOCUMENTATION_COMPLETE',
}
