export interface NotificationConfig {
  label: string;
  value: string;
}

export const notificationConfig: NotificationConfig[] = [
  {
    label: 'TEMPLATE.ACCOUNT.NOTIFICATIONS_REMINDERS.ATTORNEY_REPRESENTATIVE_NOTIFICATION.TASK_QUEUE_SECTION.ALERT_MESSAGES',
    value: 'ALERT',
  },
  {
    label: 'TEMPLATE.ACCOUNT.NOTIFICATIONS_REMINDERS.ATTORNEY_REPRESENTATIVE_NOTIFICATION.TASK_QUEUE_SECTION.WARNING_MESSAGES',
    value: 'WARNING',
  },
  {
    label: 'TEMPLATE.ACCOUNT.NOTIFICATIONS_REMINDERS.ATTORNEY_REPRESENTATIVE_NOTIFICATION.TASK_QUEUE_SECTION.BENEFICIARY_DERIVATIVE',
    value: 'BENEFICIARY_DOCUMENT',
  },
  {
    label: 'TEMPLATE.ACCOUNT.NOTIFICATIONS_REMINDERS.ATTORNEY_REPRESENTATIVE_NOTIFICATION.CLIENT_PROGRESS.REGISTRATION_COMPLETED',
    value: 'APPLICANT_REGISTRATION',
  },
  {
    label: 'TEMPLATE.ACCOUNT.NOTIFICATIONS_REMINDERS.ATTORNEY_REPRESENTATIVE_NOTIFICATION.CLIENT_PROGRESS.QUESTIONNAIRE_COMPLETED',
    value: 'QUESTIONNAIRE_COMPLETE',
  },
  {
    label: 'TEMPLATE.ACCOUNT.NOTIFICATIONS_REMINDERS.ATTORNEY_REPRESENTATIVE_NOTIFICATION.CLIENT_PROGRESS.DOCUMENTATION_COMPLETED',
    value: 'DOCUMENTATION_COMPLETE',
  },
  {
    label: 'TEMPLATE.ACCOUNT.NOTIFICATIONS_REMINDERS.ATTORNEY_REPRESENTATIVE_NOTIFICATION.TASK_QUEUE_SECTION.PENDING_DOCUMENT',
    value: 'APPLICANT_DOCUMENT',
  },
];

